#TODO: can differentiate between general (shared), gpio only, and sim only params
#TODO: Add necessary clamp param values (Ex. linear and angular velocity)
/**:
  ros__parameters:
    controller: "GPIOController" #Name of the controller plugin to instantiate. 
                      #Currently only have SimController or GPIOController
      
      #A/B pins will get mapped to LEFT/RIGHT
    pins:
      AIN1: 16
      AIN2: 13
      BIN1: 18
      BIN2: 15

      ENCA1: 0
      ENCA2: 11
      ENCB1: 9
      ENCB2: 10
      SERVO: 14
    
    motor:
      pwm_frequency: 500.0 #Hz
      max_norm_speed: 1.0  #Must be between [0.0, 1.0]

    sim:
      world_name: "custom"